[[redirects]]
  from = "https://lpgrimmett.netlify.com/*"
  to = "https://liampgrimmett.uk/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://www.lpgrimmett.netlify.com/*"
  to = "https://liampgrimmett.uk/:splat"
  status = 301
  force = true

#[[redirects]]
#  from = "https://www.liampgrimmett.uk/*"
#  to = "https://liampgrimmett.uk/:splat"
#  status = 301
#  force = true